ManutencaoPlano/Models/ErrorViewModel.cs
using System;

namespace ManutencaoPlano.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ManutencaoPlano/Models/FtAbateQuarteioHabilitacao.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace ManutencaoPlano.Models
{   
    public partial class FtAbateQuarteioHabilitacao
    {
        [DisplayName("Banco")]
        public string Cbd { get; set; }

        [DisplayName("Data")]
        public DateTime? Dmovimento { get; set; }

        [DisplayName("Sequencial")]
        public int? Isequencial { get; set; }

        public int? Ibanda { get; set; }

        [DisplayName("Cód Empresa")]
        public int? Ncdempresaabate { get; set; }
        public int? Ncdempresaproducao { get; set; }
        public int? Ncdproduto { get; set; }

        [DisplayName("Tipo")]
        public string Cquarto { get; set; }
        public string Ccdbarra { get; set; }
        public DateTime? Dvalidade { get; set; }
        public double? Npesobruto { get; set; }
        public int? Iidade { get; set; }

        [DisplayName("Sexo")]
        public string Csexo { get; set; }

        [DisplayName("Peso")]
        public double? Npeso { get; set; }
        public int? Ncdhistoricoentrada { get; set; }
        public DateTime? Dentradaestoque { get; set; }

        [DisplayName("Motivo Saída")]
        public int? Ncdhistoricosaida { get; set; }
        public DateTime? Dsaidaestoque { get; set; }
        public int? Ncdcaracteristica { get; set; }
        public int? Ncdhabilitacaocompragado { get; set; }
        public int? Ncdhabilitacaocalhasangria { get; set; }
        public int? Ncdhabilitacaotipificacao { get; set; }

        [DisplayName("Habilitação")]
        public int? Ncdhabilitacaocamara { get; set; }
        public int? Ncdhabilitacaotransferencia { get; set; }
        public int? Ncdhabilitacaoordemproducao { get; set; }
        public int? Ncdordemproducao { get; set; }
        public int? Ncdtipoproducao { get; set; }
        public int? Ncdhabilitacaoescala { get; set; }
        public int? Ncdhabilitacaorecebimento { get; set; }
    }

}

ManutencaoPlano/Models/ViewDisponibilidadeQuartos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace ManutencaoPlano.Models
{
    public partial class ViewDisponibilidadeQuartos
    {
        public int? Icodigoempresa { get; set; }
        public string Csigla { get; set; }
        public int? Isif { get; set; }

        [DisplayName("Fechamento")]
        public DateTime? Ddatafechamento { get; set; }
        public string Ctipoquarto { get; set; }

        [DisplayName("Estocagem")]
        public string Ccamaradeestocagem { get; set; }

        [DisplayName("Qtd Pçs")]
        public long? Total { get; set; }

        [DisplayName("CHL")]
        public long? Chl { get; set; }

        [DisplayName("SAU")]
        public long? Sau { get; set; }

        [DisplayName("EGY")]
        public long? Egy { get; set; }

        [DisplayName("PSR")]
        public long? Psr { get; set; }

        [DisplayName("MI")]
        public long? Mi { get; set; }

        [DisplayName("Até 2=")]
        public long? Ate2 { get; set; }

        [DisplayName("2+")]
        public long? _2 { get; set; }

        [DisplayName("3-")]
        public long? _3 { get; set; }

        [DisplayName("3=")]
        public long? _31 { get; set; }

        [DisplayName("3+ UP")]
        public long? _3Up { get; set; }

        [DisplayName("PESO")]
        public double? Media { get; set; }
    }


}

ManutencaoPlano/ViewModels/EntradaProducaoViewModel.cs
using System.Collections.Generic;
using ManutencaoPlano.Models;

namespace ManutencaoPlano.ViewModels
{
    public class EntradaProducaoViewModel
    {
        public IEnumerable<ViewDisponibilidadeQuartos> DisponibilidadeQuartos { get; set;}

        public List<string> ListaEmpresa { get; set;}
    }
}

ManutencaoPlano/Controllers/EntradaProducaoController.cs
using ManutencaoPlano.Data;
using ManutencaoPlano.Models;
using ManutencaoPlano.Repositorio;
using ManutencaoPlano.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

namespace ManutencaoPlano.Controllers
{
    public class EntradaProducaoController : Controller
    {

        private readonly IEntradaProducaoRepositorio _entradaProducaoRepositorio;

        public EntradaProducaoController(IEntradaProducaoRepositorio entradaProducaoRepositorio)
        {
            _entradaProducaoRepositorio = entradaProducaoRepositorio;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Tabela(string tipo, string unidade)
        {
            ViewBag.PlantaAtual = unidade;
            ViewBag.TipoAtual = tipo;

            var entradaProducaoViewModel = new EntradaProducaoViewModel();
            
            entradaProducaoViewModel.DisponibilidadeQuartos = _entradaProducaoRepositorio.BuscarPorTipo(tipo, unidade); 

            List<string> SiglasEmpresas = (from siglas in entradaProducaoViewModel.DisponibilidadeQuartos
                select siglas.Csigla).Distinct().ToList();

            List<DateTime?> DtFechamento = (from fechamento in entradaProducaoViewModel.DisponibilidadeQuartos
                select fechamento.Ddatafechamento).Distinct().ToList();

            List<string> Camaras = (from cm in entradaProducaoViewModel.DisponibilidadeQuartos
                select cm.Ccamaradeestocagem).Distinct().ToList();

            var Tipo = (from tp in entradaProducaoViewModel.DisponibilidadeQuartos
                           select tp.Ctipoquarto).Distinct().ToString();

            ViewBag.Siglas = SiglasEmpresas;
            ViewBag.DtFechamento = DtFechamento;
            ViewBag.Camaras = Camaras;
            
            

            return View(entradaProducaoViewModel);
        }

        public IActionResult TabelaParcial(string tipo, string unidade)
        {
            return ViewComponent("TabelaParcial",
                new
                {
                    tipo = tipo,
                    unidade = unidade
                }
            );
        }
        

    }
}

ManutencaoPlano/Controllers/HomeController.cs
using ManutencaoPlano.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ManutencaoPlano.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ManutencaoPlano/ViewComponents/TabelaParcialViewComponent.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using ManutencaoPlano.Models;
using ManutencaoPlano.Data;
using ManutencaoPlano.Repositorio;
using ManutencaoPlano.Controllers;
using ManutencaoPlano.ViewModels;

namespace ManutencaoPlano.ViewComponents
{
    public class TabelaParcialViewComponent : ViewComponent
    {
        private readonly IEntradaProducaoRepositorio _entradaProducaoRepositorio;

        public TabelaParcialViewComponent(IEntradaProducaoRepositorio entradaProducaoRepositorio)
        {
            _entradaProducaoRepositorio = entradaProducaoRepositorio;
        }

        public async Task<IViewComponentResult> InvokeAsync(string tipo, string unidade)
        {
   
            var tabela = _entradaProducaoRepositorio.BuscarPorTipo(tipo, unidade);

            return View(tabela);

        }
    }
}

ManutencaoPlano/Views/EntradaProducao/Index.cshtml
@using System.IO
@{
    ViewData["Title"] = "Entrada de produção";
}

<div class="container">

    <div class="card-columns">

        <div class="card p-1 text-center shadow-sm">
            <h3 class="">Banda</h3>
            <div class="card-body text-center text-primary">
                <img src="~/png/meia-carcaca-bovina.png" style="height: 8rem; filter: invert(100%)"/>
                <p class="card-text text-dark"></p>
                <a class="text-primary stretched-link text-right d-block" asp-area="" asp-route-tipo="BANDA" asp-route-unidade="" asp-controller="EntradaProducao" asp-action="Tabela"><strong>Acessar</strong></a>
            </div>
        </div>

        <div class="card p-1 text-center shadow-sm">
            <h3 class="">Traseiro</h3>
            <div class="card-body text-center text-primary">
                <img src="~/png/traseiro-serrote.png" style="height: 8rem; filter: invert(100%)"/>
                <p class="card-text text-dark"></p>
                <a class="text-primary stretched-link text-right d-block" asp-area="" asp-route-tipo="TRASEIRO" asp-route-unidade="" asp-controller="EntradaProducao" asp-action="Tabela"><strong>Acessar</strong></a>
            </div>
        </div>

        <div class="card p-1 text-center shadow-sm">
            <h3 class="">Dianteiro</h3>
            <div class="card-body text-center text-primary">
                <img src="~/png/dianteiro-com-peito.png" style="height: 8rem; filter: invert(100%)"/>
                <p class="card-text text-dark"></p>
                    <a class="text-primary stretched-link text-right d-block" asp-area="" asp-route-tipo="DIANTEIRO" asp-route-unidade="" asp-controller="EntradaProducao" asp-action="Tabela"><strong>Acessar</strong></a>
            </div>
        </div>

        <div class="card p-1 text-center shadow-sm">
            <h3 class="">Ponta de Agulha</h3>
            <div class="card-body text-center text-primary">
                <img src="~/png/costela-inteira.png" style="height: 8rem; filter: invert(100%)"/>
                <p class="card-text text-dark"></p>
                    <a class="text-primary stretched-link text-right d-block" asp-area="" asp-route-tipo="PA" asp-route-unidade="" asp-controller="EntradaProducao" asp-action="Tabela"><strong>Acessar</strong></a>
            </div>
        </div>

    </div>

</div>

ManutencaoPlano/Views/EntradaProducao/Tabela.cshtml
@model EntradaProducaoViewModel
@section Scripts {
    <script>
        function atualizarPartial(parametro) {
            var url = "/EntradaProducao/TabelaParcial/@ViewBag.TipoAtual/"; //TROCAR PARAMETRO TIPO DE PRODUÇÃO
            if (parametro) {
                var url = url + encodeURIComponent(parametro);
            }
            $('#disponibilidade').load(url);
        }

        $(document).ready(function () {
            $("#atualizar-botao").click(function () {
                var parametro = $("#parametro-dropdown").val();
                atualizarPartial(parametro);
            });
        });
    </script>
}

@{
    ViewData["Title"] = "Entrada de produção";
}

<div id="partial-view-container">
    <div>
        <p>@ViewBag.TipoAtual</p>

        <select id="parametro-dropdown" class="btn btn-primary">
            @foreach (var item in ViewBag.Siglas)
            {
                <option value="@item">@item</option>
            }
        </select>
        <button class="btn btn-primary" id="atualizar-botao">Atualizar</button>
    </div>
</div>


<div id="disponibilidade" class="text-center table-responsive">
    @await Component.InvokeAsync("TabelaParcial", new { tipo = @ViewBag.TipoAtual, unidade = "PDP" })
</div>

ManutencaoPlano/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <div class="card-columns">
        <div class="card p-1 text-center shadow-sm">
            <h3 class="">Entradas</h3>
            <div class="card-body text-center text-primary">
                <img src="~/png/volumes-lupa.png" style="height: 8rem;"/>
                <p class="card-text text-dark">Filtro para desenho de volumes</p>
                <a class="text-primary stretched-link text-right d-block" asp-area=""  asp-controller="EntradaProducao" asp-action="Index"><strong>Acessar</strong></a>
            </div>
        </div>

         <div class="card p-1 text-center shadow-sm">
            <h3 class="">Premissas</h3>
            <div class="card-body text-center text-primary">
                <img src="~/png/premissas.png" style="height: 8rem;"/>
                <p class="card-text text-dark">Regras p/ manutenção do plano</p>
                <a class="text-primary stretched-link text-right d-block" asp-area=""  asp-controller="Premissas" asp-action="Index"><strong>Acessar</strong></a>
            </div>
        </div>

        <div class="card p-1 text-center shadow-sm">
            <h3 class="">Plano</h3>
            <div class="card-body text-center text-primary">
                <img src="~/png/plano.png" style="height: 8rem;"/>
                <p class="card-text text-dark">Planejamento proposto</p>
                <a class="text-primary stretched-link text-right d-block" asp-area=""  asp-controller="Plano" asp-action="Index"><strong>Acessar</strong></a>
            </div>
        </div>
    </div>
</div>

ManutencaoPlano/Views/Shared/Components/TabelaParcial/Default.cshtml
@model IEnumerable<ViewDisponibilidadeQuartos>

<table class="table-hover table-bordered">
    <tr>
        <th class="colunas__principais" rowspan="2" colspan="1">Fechamento</th>
        <th class="colunas__principais" colspan="2">Câmaras</th>
        <th class="colunas__principais" colspan="5">Habilitações</th>
        <th class="colunas__principais" colspan="5">Tipificação</th>
        <th class="colunas__principais" rowspan="2" colspan="1">Média</th>
    </tr>
    <tr class="colunas__secundarias">
        <!--<th>@Html.//DisplayNameFor(model => model.Ddatafechamento)</th>-->
        <th>@Html.DisplayNameFor(model => model.Ddatafechamento)</th>
        <th>@Html.DisplayNameFor(model => model.Total)</th>
        <th>@Html.DisplayNameFor(model => model.Chl)</th>
        <th>@Html.DisplayNameFor(model => model.Sau)</th>
        <th>@Html.DisplayNameFor(model => model.Egy)</th>
        <th>@Html.DisplayNameFor(model => model.Psr)</th>
        <th>@Html.DisplayNameFor(model => model.Mi)</th>
        <th>@Html.DisplayNameFor(model => model.Ate2)</th>
        <th>@Html.DisplayNameFor(model => model._2)</th>
        <th>@Html.DisplayNameFor(model => model._3)</th>
        <th>@Html.DisplayNameFor(model => model._31)</th>
        <th>@Html.DisplayNameFor(model => model._3Up)</th>
        <!--<th>@Html.//DisplayNameFor(model => model.Media)</th>-->

    </tr>
    @foreach (var item in Model)
    {
        <tr class="dados__tabela">
            <td>@Html.DisplayFor(modelItem => item.Ddatafechamento)</td>
            <td>@Html.DisplayFor(modelItem => item.Ccamaradeestocagem)</td>
            <td>@Html.DisplayFor(modelItem => item.Total)</td>
            <td>@Html.DisplayFor(modelItem => item.Chl)</td>
            <td>@Html.DisplayFor(modelItem => item.Sau)</td>
            <td>@Html.DisplayFor(modelItem => item.Egy)</td>
            <td>@Html.DisplayFor(modelItem => item.Psr)</td>
            <td>@Html.DisplayFor(modelItem => item.Mi)</td>
            <td>@Html.DisplayFor(modelItem => item.Ate2)</td>
            <td>@Html.DisplayFor(modelItem => item._2)</td>
            <td>@Html.DisplayFor(modelItem => item._3)</td>
            <td>@Html.DisplayFor(modelItem => item._31)</td>
            <td>@Html.DisplayFor(modelItem => item._3Up)</td>
            <td>@Html.DisplayFor(modelItem => item.Media) kg</td>
        </tr>
    }
</table>

ManutencaoPlano/Views/Shared/_Layout.cshtml
@{
    var EntradaProducaoClass = this.ViewContext.RouteData.Values["controller"].ToString() == "EntradaProducao" ? "active" : "";
    var PremissasClass = this.ViewContext.RouteData.Values["controller"].ToString() == "Premissas" ? "active" : "";
    var PlanoClass = this.ViewContext.RouteData.Values["controller"].ToString() == "Plano" ? "active" : "";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Planejamento de produção</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/css/tabela.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-dark" asp-area="" asp-controller="Home" asp-action="Index">Manutenção do Plano</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>



                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 nav-pills font-weight-bold">
                        <li class="nav-item mx-2">
                            <a class="nav-link nav-primary @EntradaProducaoClass" asp-area="" asp-controller="EntradaProducao" asp-action="Index">Entradas</a>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="btn-group nav-link @PremissasClass" asp-area="" asp-controller="Home" asp-action="Privacy">Premissas</a>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="btn-group nav-link @PlanoClass" asp-area="" asp-controller="Home" asp-action="Privacy">Plano</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">

            @RenderBody()

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid">
            &copy; 2023 - ManutencaoPlano - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>